// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type Map struct {
	ID   int64
	Uid  int64
	Turn string
	Clan string
	Path string
}

type Report struct {
	ID   int64
	Uid  int64
	Turn string
	Clan string
	Path string
}

type Session struct {
	ID          string
	Uid         int64
	ExpiresDttm time.Time
}

type Unit struct {
	Rid         int64
	Turn        string
	Name        string
	StartingHex string
	EndingHex   string
}

type User struct {
	ID             int64
	Handle         string
	HashedPassword string
	Clan           string
	MagicKey       string
	Path           string
	Crdttm         time.Time
	Updttm         time.Time
}
