// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Role struct {
	RoleID      int64
	Role        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Server struct {
	AssetsPath    string
	TemplatesPath string
	Salt          string
}

type Session struct {
	SessID    string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	UserID         int64
	Email          string
	Timezone       string
	IsActive       int64
	HashedPassword string
	Clan           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastLogin      time.Time
}

type UserRole struct {
	UserID    int64
	RoleID    int64
	CreatedAt time.Time
}
