// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Session struct {
	SessID    string
	UserID    int64
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	UserID         int64
	Email          string
	Timezone       string
	IsActive       int64
	HashedPassword string
	Clan           string
	Role           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastLogin      time.Time
}
