// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Server struct {
	AssetsPath    string
	TemplatesPath string
	Salt          string
}

type Session struct {
	SessID    string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	UserID          int64
	Email           string
	Timezone        string
	IsActive        int64
	HashedPassword  string
	MagicLink       string
	Clan            string
	IsAdministrator int64
	IsOperator      int64
	IsUser          int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	LastLogin       time.Time
}
