// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: server.sql

package sqlc

import (
	"context"
)

const setServerAssetsPath = `-- name: SetServerAssetsPath :exec

UPDATE server
SET assets_path = ?1
`

//	Copyright (c) 2024 Michael D Henderson. All rights reserved.
//
// SetServerAssetsPath sets the path to the assets directory for the server.
func (q *Queries) SetServerAssetsPath(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, setServerAssetsPath, path)
	return err
}

const setServerSalt = `-- name: SetServerSalt :exec
UPDATE server
SET salt = ?1
`

// SetServerSalt sets the salt for the server.
func (q *Queries) SetServerSalt(ctx context.Context, salt string) error {
	_, err := q.db.ExecContext(ctx, setServerSalt, salt)
	return err
}

const setServerTemplatesPath = `-- name: SetServerTemplatesPath :exec
UPDATE server
SET templates_path = ?1
`

// SetServerTemplatesPath sets the path to the templates directory for the server.
func (q *Queries) SetServerTemplatesPath(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, setServerTemplatesPath, path)
	return err
}
